### ISSUE TITLE
`Fatal error: could not load resource bundle` when using packages with resources

### ISSUE THREAD

**Issue by alfavata** [SwiftXcode/swift-lambda#5]
I'm trying to integrate [PhoneNumberKit](https://github.com/marmelroy/PhoneNumberKit) in my lambda, and according to [this PR](https://github.com/marmelroy/PhoneNumberKit/pull/429) it should work on Linux servers.

However, when I build and deploy my lambda using `swift-lambda` it encounters the following error:
```
Fatal error: could not load resource bundle: from /var/task/PhoneNumberKit_PhoneNumberKit.resources or /Users/alfavata/Code/ios-hiya/CallLogLambda/.build/x86_64-unknown-linux/release/PhoneNumberKit_PhoneNumberKit.resources: file PhoneNumberKit/resource_bundle_accessor.swift, line 11
```

(Note that it's referring to the path on my local machine)

I've put a minimal example package [here](https://github.com/alfavata/swift-lambda-phonenumberkit-example) as suggested by @helje5

**Comment by helje5** [comment]
Works now.
